# Details of a system configuration
---
interval: 2000 #UI事件轮询间隔（毫秒），默认2000毫秒
maximumSize: 10000 #Caffeine缓存最大行数，默认10000行
expireAfterWrite: 5 #Caffeine缓存expireAfterWrite（分钟）
refreshAfterWrite: 1 #Caffeine缓存refreshAfterWrite（分钟）
--- #end